const router = require('express').Router()
const accomodationController = require('../controllers/accomodationControllers')
const { auth } = require("../middlewares/authentication")
const { validateAccomodation, validateDeleteMultipleAccod } = require('../middlewares/validate')
router.get('/', auth, accomodationController.getAccomodations)
router.get('/:id', auth, accomodationController.getdata)
router.post('/', auth, validateAccomodation, accomodationController.createAccomodation)
router.put('/:id', auth, validateAccomodation, accomodationController.updateAccomodation)
router.delete('/:id', auth, accomodationController.deleteAccomodation)
router.put('/update-state/:id', auth, accomodationController.updateRentedStatus)
router.get('/user/accomod',auth, accomodationController.getUserListAccomod )
router.post('/delete-multiple', auth, validateDeleteMultipleAccod, accomodationController.deleteMultiple )
router.get('/renter/list', auth, accomodationController.getListRenter)
router.post('/increase-like/:id', auth, accomodationController.increaseLikes)
router.post('/increase-view/:id', auth, accomodationController.increseViews)
module.exports = router